# Generated by Django 3.0.8 on 2020-07-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of collection creation')),
                ('access_type', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('protected', 'protected')], default='public', max_length=10)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
            ],
        ),
    ]
