# Generated by Django 3.0.8 on 2020-07-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copy_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('protected', 'protected')], default='public', max_length=10)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IterativeCCardNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
                ('from_val', models.IntegerField()),
                ('to_val', models.IntegerField()),
                ('step_val', models.IntegerField()),
                ('autoCopy', models.BooleanField(default=False)),
                ('random', models.BooleanField(default=False)),
                ('ccollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copy_board.CCollection')),
            ],
        ),
        migrations.CreateModel(
            name='RegularCCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('copy_content', models.TextField(verbose_name='Content to be copied')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
                ('ccollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copy_board.CCollection')),
            ],
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
