# Generated by Django 3.0.8 on 2020-07-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copy_board', '0002_auto_20200718_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccollection',
            options={'verbose_name': 'CCollection', 'verbose_name_plural': 'CCollections'},
        ),
        migrations.AlterModelOptions(
            name='iterativeccardnumber',
            options={'verbose_name': 'Iterative ccard(number)', 'verbose_name_plural': 'Iterative ccards(number)'},
        ),
        migrations.AlterModelOptions(
            name='regularccard',
            options={'verbose_name': 'Regular ccard', 'verbose_name_plural': 'Regular ccards'},
        ),
        migrations.RenameField(
            model_name='iterativeccardnumber',
            old_name='autoCopy',
            new_name='auto_copy',
        ),
        migrations.AlterField(
            model_name='iterativeccardnumber',
            name='ccollection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='copy_board.CCollection'),
        ),
        migrations.AlterField(
            model_name='regularccard',
            name='ccollection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='copy_board.CCollection'),
        ),
    ]
