# Generated by Django 3.0.8 on 2020-07-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_board', '0003_auto_20200719_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterativeccardnumber',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
