# Generated by Django 3.0.8 on 2020-07-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copy_board', '0004_iterativeccardnumber_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='IterativeCCardText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
                ('content', models.TextField()),
                ('delimiter', models.CharField(max_length=50)),
                ('remove_whitespace', models.BooleanField(default=False)),
                ('auto_copy', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('random', models.BooleanField(default=False)),
                ('ccollection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='copy_board.CCollection')),
            ],
            options={
                'verbose_name': 'Iterative ccard(text)',
                'verbose_name_plural': 'Iterative ccards(text)',
            },
        ),
    ]
