# Generated by Django 3.0.8 on 2020-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_board', '0005_iterativeccardtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterativeccardnumber',
            name='endless',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iterativeccardnumber',
            name='to_val',
            field=models.IntegerField(null=True),
        ),
    ]
