# Generated by Django 3.0.8 on 2020-08-01 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copy_board', '0008_auto_20200726_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('protected', 'protected')], default='public', max_length=10)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CCollection',
                'verbose_name_plural': 'CCollections',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='NumberCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
                ('index', models.IntegerField()),
                ('from_val', models.IntegerField()),
                ('to_val', models.IntegerField(null=True)),
                ('step_val', models.IntegerField()),
                ('auto_copy', models.BooleanField(default=False)),
                ('endless', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('random', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='copy_board.Collection')),
            ],
            options={
                'verbose_name': 'Iterative ccard(number)',
                'verbose_name_plural': 'Iterative ccards(number)',
            },
        ),
        migrations.CreateModel(
            name='RegularCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
                ('index', models.IntegerField()),
                ('copy_content', models.TextField(max_length=2000, verbose_name='Content to be copied')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='copy_board.Collection')),
            ],
            options={
                'verbose_name': 'Regular ccard',
                'verbose_name_plural': 'Regular ccards',
            },
        ),
        migrations.CreateModel(
            name='TextCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('indigo', 'Indigo')], default=('blue', 'Blue'), max_length=10)),
                ('index', models.IntegerField()),
                ('content', models.TextField()),
                ('delimiter', models.CharField(max_length=50)),
                ('remove_whitespace', models.BooleanField(default=False)),
                ('auto_copy', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('random', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='copy_board.Collection')),
            ],
            options={
                'verbose_name': 'Iterative ccard(text)',
                'verbose_name_plural': 'Iterative ccards(text)',
            },
        ),
        migrations.RemoveField(
            model_name='iterativeccardnumber',
            name='ccollection',
        ),
        migrations.RemoveField(
            model_name='iterativeccardtext',
            name='ccollection',
        ),
        migrations.RemoveField(
            model_name='regularccard',
            name='ccollection',
        ),
        migrations.DeleteModel(
            name='CCollection',
        ),
        migrations.DeleteModel(
            name='IterativeCCardNumber',
        ),
        migrations.DeleteModel(
            name='IterativeCCardText',
        ),
        migrations.DeleteModel(
            name='RegularCCard',
        ),
    ]
