# Generated by Django 3.0.8 on 2020-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_board', '0009_auto_20200801_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='numbercard',
            options={'verbose_name': 'Iterative card(number)', 'verbose_name_plural': 'Iterative cards(number)'},
        ),
        migrations.AlterModelOptions(
            name='regularcard',
            options={'verbose_name': 'Regular card', 'verbose_name_plural': 'Regular cards'},
        ),
        migrations.AlterModelOptions(
            name='textcard',
            options={'verbose_name': 'Iterative card(text)', 'verbose_name_plural': 'Iterative cards(text)'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='public', max_length=10),
        ),
    ]
