# Generated by Django 3.0.8 on 2020-08-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_board', '0011_collection_last_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
